
import java.util.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DELL
 */
public class App extends javax.swing.JFrame {

    /**
     * Creates new form App
     */
    
    ClosestPairOfPoints cpp = new ClosestPairOfPoints();
    static StringBuilder logs;
    
    public App() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        points = new javax.swing.JTextField();
        loops = new javax.swing.JTextField();
        start = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        log = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bft = new javax.swing.JTextField();
        dnct = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        minx = new javax.swing.JTextField();
        maxx = new javax.swing.JTextField();
        miny = new javax.swing.JTextField();
        maxy = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        sukses = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        indikator = new javax.swing.JTextField();
        reset = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Closest Pair of Points Problem ~ DnC vs Brute Force");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setText("Masukkan banyak points per perulangan");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 51));
        jLabel2.setText("Masukkan Banyak perulangan");

        start.setForeground(new java.awt.Color(0, 51, 51));
        start.setText("START");
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });

        log.setEditable(false);
        log.setColumns(20);
        log.setFont(new java.awt.Font("Yu Gothic", 0, 15)); // NOI18N
        log.setRows(5);
        jScrollPane1.setViewportView(log);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Total Waktu Brute Force");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Total Waktu DnC");

        bft.setEditable(false);

        dnct.setEditable(false);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("ms");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("ms");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 51));
        jLabel7.setText("Min x");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 51));
        jLabel8.setText("Max x");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 51));
        jLabel9.setText("Min y");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 51));
        jLabel10.setText("Max y");

        minx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minxActionPerformed(evt);
            }
        });

        maxx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxxActionPerformed(evt);
            }
        });

        miny.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minyActionPerformed(evt);
            }
        });

        maxy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxyActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Sukses");

        sukses.setEditable(false);

        indikator.setEditable(false);
        indikator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                indikatorActionPerformed(evt);
            }
        });

        reset.setText("RESET");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bft)
                            .addComponent(dnct, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                            .addComponent(sukses))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(39, 39, 39)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(91, 91, 91)
                                    .addComponent(points, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(loops, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(reset, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(start, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel8))
                                    .addGap(34, 34, 34)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(maxx, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(minx, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(36, 36, 36)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel10))
                                    .addGap(34, 34, 34)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(maxy, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(170, 170, 170))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(miny, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(88, 88, 88)))))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel12)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(indikator, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 704, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(133, 133, 133)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(points, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(loops, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel7)
                                        .addComponent(minx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel8)
                                        .addComponent(maxx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel9)
                                        .addComponent(miny, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(start, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(maxy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel10)
                                        .addComponent(reset))))))
                    .addComponent(indikator, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sukses, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(bft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(dnct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
        // kebutuhan log, input, dan waktu 
        logs = new StringBuilder();
        int totalLoop = Integer.parseInt(points.getText());
        int totalPointsPerLoop = Integer.parseInt(loops.getText());
        
        double minX = Double.parseDouble(minx.getText());
        double maxX = Double.parseDouble(maxx.getText());
        double minY = Double.parseDouble(miny.getText());
        double maxY = Double.parseDouble(maxy.getText());
        
        int passed = 0;
        long nlognTime = 0;
        long nsqTime = 0;
        long startTime;
        
        String msg = "\nMenjalankan " + totalLoop + " cases, setiap case memiliki " + totalPointsPerLoop + " points atau koordinat\n\n";
        logs.append(msg);
        
        for(int k=0;k<totalLoop;k++){
            Point[] ps = cpp.generateRandomPoints(totalPointsPerLoop, maxX, minX, maxY, minY);
            startTime = new Date().getTime();

            Point[] pair = cpp.getClosestPair(ps);
            nlognTime += (new Date().getTime() - startTime);

            double distance = cpp.getDistance(pair);
            logs.append("[ok] = " + pair[0].toString() + "," + pair[1].toString() + " = " + distance + "\n");

            startTime = new Date().getTime();
            pair = cpp.bruteForce(ps);

            nsqTime += (new Date().getTime() - startTime);
            double distance2 = cpp.getDistance(pair);
            if(distance==distance2){
                    passed++;
            }
        }
        
        indikator.setText("Done");
        log.setText(logs.toString());
        sukses.setText(passed + "/" + totalLoop);
        bft.setText(String.valueOf(nsqTime));
        dnct.setText(String.valueOf(nlognTime));
    }//GEN-LAST:event_startActionPerformed

    private void minxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_minxActionPerformed

    private void maxxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maxxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maxxActionPerformed

    private void minyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_minyActionPerformed

    private void maxyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maxyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maxyActionPerformed

    private void indikatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_indikatorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_indikatorActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // set button
        points.setText("");
        loops.setText("");
        minx.setText("");
        miny.setText("");
        maxx.setText("");
        maxy.setText("");
        indikator.setText("");
        log.setText("");
        sukses.setText("");
        bft.setText("");
        dnct.setText("");
    }//GEN-LAST:event_resetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                App app = new App();
                app.setLocationRelativeTo(null);
                app.setResizable(false);
                app.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bft;
    private javax.swing.JTextField dnct;
    private javax.swing.JTextField indikator;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea log;
    private javax.swing.JTextField loops;
    private javax.swing.JTextField maxx;
    private javax.swing.JTextField maxy;
    private javax.swing.JTextField minx;
    private javax.swing.JTextField miny;
    private javax.swing.JTextField points;
    private javax.swing.JButton reset;
    private javax.swing.JButton start;
    private javax.swing.JTextField sukses;
    // End of variables declaration//GEN-END:variables
}

class ClosestPairOfPoints {
    // generate titik acak 
    public Point[] generateRandomPoints(int size,double maxX, double minX,double maxY,double minY){
        Point[] points = new Point[size];
        for(int i=0;i<size;i++){
            points[i] = new Point(
                Math.random()*(maxX-minX) + minX,
                Math.random()*(maxY-minY) + minY);
        }
        return points;
    }
	
    // = √(x2−x1)^2+(y2−y1)^2  
    public double getDistance(Point[] ps) {
        if(ps==null||ps.length!=2){
            return -1;
        }
        return Math.pow(
            (ps[0].x-ps[1].x) * (ps[0].x-ps[1].x) + 
            (ps[0].y-ps[1].y) * (ps[0].y-ps[1].y), 0.5);
    }

    public Point[] bruteForce(Point[] ps){
        if(ps.length==2){
            return ps;
        }
        Point[] pair = new Point[2];
        Point[] temp = new Point[2];
        double min = Double.MAX_VALUE;
        for(int i=0;i<ps.length;i++)
            for(int j=i+1;j<ps.length;j++){
                temp[0] = ps[i];
                temp[1] = ps[j];
                double dis = this.getDistance(temp);
                if(dis<min){
                        min = dis;
                        pair[0] = temp[0];
                        pair[1] = temp[1];
                }
            }
        return pair;
    }

    public Point[] getClosestPair(Point[] ps){
        // urutkan berdasarkan absis x
        sortPointsByX(ps);

        // kemudian hitung
        return getClosestPair(ps,0,ps.length-1);
    }

    /**
     * menggunakan quick sort
     * kompleksitas: O(n log n)
     */
    public void sortPointsByX(Point[] ps) {
        int size = ps.length;
        quickSort(ps,0,size-1);
    }

    public void quickSort(Point[] ps, int left, int right) {
        if (left >= right)
            return;
        int i = left, j = right;
        Point tmp;
        double pivot = (ps[left].x + ps[right].x) / 2;

        while (i <= j) {
            while (ps[i].x < pivot)
                i++;
            while (ps[j].x > pivot)
                j--;
            if (i <= j) {
                tmp = ps[i];
                ps[i] = ps[j];
                ps[j] = tmp;
                i++;
                j--;
            }
        }

        if (left < i - 1)
            quickSort(ps, left, i - 1);
        if (i < right)
            quickSort(ps, i, right);
    }
	
    /**
     * @param ps: sebelumnya udah di sort berdasarkan absis
     */
    public Point[] getClosestPair(Point[] ps, int start, int end){
        if(start==end)
            return null;
        if(start+1==end)
            return new Point[]{ps[start],ps[end]};

        // menentukan medium X
        int mediumX = (start+end)/2;
        
        // kemudian solve secara rekursif
        Point[] leftClosestPair = this.getClosestPair(ps, start, mediumX);
        Point[] rightCloestPair = this.getClosestPair(ps, mediumX, end);
        Point[] returnPair;
        double returnDelta;


        // cari minimal distance untuk masing-masing (sebelah kiri dan kanan)
        double leftDelta = this.getDistance(leftClosestPair);
        double rightDelta = this.getDistance(rightCloestPair);
        double delta;
        if(leftDelta < rightDelta){
            delta = leftDelta;
            returnPair = leftClosestPair;
        }else{
            delta = rightDelta;
            returnPair = rightCloestPair;
        }
        returnDelta = delta;
        
        // mentukan jarak minimal antara pasangan titik yg terletak di satu sisi dan yg terletak di sisi lain
        int leftEdge = this.getLeftEdgeOfDelta(ps, mediumX, leftDelta);
        if(leftEdge < start)
            leftEdge = start;
        int rightEdge = this.getRightEdgeOfDelta(ps, mediumX, rightDelta);
        if(rightEdge > end)
            rightEdge = end;

        // urutkan points yang edge sebelah kiri dan kanan berdasarkan ordinat atau Y
        // Time: O(n log n)
        int yOrderInfo[][] = this.sortPointsByY(ps,leftEdge,rightEdge);
        int idxToOrderY[] = yOrderInfo[0];
        int orderYToIdx[] = yOrderInfo[1];

        // periksa apakah ada titik di [mediumX, rightEdge] yang memiliki jarak kurang dari delta ke titik ini
        for(int i=leftEdge;i<=mediumX;i++){
            int orderY = idxToOrderY[i-leftEdge];
            for(int j=orderY-1;j>=0;j--){
                Point[] pair = new Point[]{ps[i],ps[orderYToIdx[j]]};
                if(this.getYDistance(pair) > delta)
                    break;
                double distance = this.getDistance(pair);
                if(distance < returnDelta){
                    returnDelta = distance;
                    returnPair = pair;
                }
            }

            for(int j=orderY+1;j<idxToOrderY.length;j++){
                Point[] pair = new Point[]{ps[i],ps[orderYToIdx[j]]};
                if(this.getYDistance(pair) > delta)
                    break;
                double distance = this.getDistance(pair);
                if(distance < returnDelta){
                    returnDelta = distance;
                    returnPair = pair;
                }				
            }
        }
        return returnPair;
    }
	
    // mengurutkan ordinat menggunakan quick sort, cost n log n
    public int[][] sortPointsByY(Point[] ps, int leftEdge, int rightEdge) {
        int size = rightEdge - leftEdge + 1;
        int orderToIdx[] = new int[size];
        for(int i=0;i<size;i++)
                orderToIdx[i] = leftEdge+i;
        quickSortForDeltaArea(ps, orderToIdx, 0, size-1);
        int idxToOrder[] = new int[size];
        for(int i=0;i<size;i++){
                idxToOrder[orderToIdx[i]-leftEdge] = i;
        }
        return new int[][]{idxToOrder,orderToIdx};
    }
	
    // quick sort untuk delta area, kiri medium & kanan medium
    public void quickSortForDeltaArea(Point[] ps,int[] indexs, int left, int right) {
        if (left >= right)
            return;
        int i = left, j = right;
        int tmp;
        double pivot = ( ps[indexs[left]].y + ps[indexs[right]].y) / 2;

        while (i <= j) {
            while (ps[indexs[i]].y < pivot)
                i++;
            while (ps[indexs[j]].y > pivot)
                j--;
            if (i <= j) {
                tmp = indexs[i];
                indexs[i] = indexs[j];
                indexs[j] = tmp;
                i++;
                j--;
            }
        }


        if (left < i - 1)
            quickSortForDeltaArea(ps, indexs, left, i - 1);
        if (i < right)
            quickSortForDeltaArea(ps, indexs, i, right);
    }

    // hitung tepi kanan area delta 
    public int getRightEdgeOfDelta(Point[] ps, int mediumX, double rightDelta) {
        for(int i=mediumX;i<ps.length;i++){
            if(ps[i].x - ps[mediumX].x>rightDelta)
                return i-1;
        }
        return ps.length-1;
    }

    // hitung tepi kiri area delta 
    public int getLeftEdgeOfDelta(Point[] ps, int mediumX, double leftDelta) {
        for(int i=mediumX;i>=0;i--){
            if(ps[mediumX].x - ps[i].x>leftDelta)
                return i+1;
        }
        return 0;
    }
	
    // y distance
    public double getYDistance(Point[] ps) {
        return Math.abs(ps[0].y - ps[1].y);
    }
}

class Point{
    public double x;
    public double y;
    public Point(double x,double y){
        this.x = x;
        this.y = y;
    }
    public String toString(){
        return "("+x+","+y+")";
    }
}
